### ISSUE TITLE
does not work with VS2013

### ISSUE THREAD

**Issue by mazj** [jsargiot/visual-coverage#11]
Unable to load DLL 'Microsoft.VisualStudio.Coverage.Symbols.dll'

Unhandled Exception: Microsoft.VisualStudio.Coverage.Analysis.CoverageAnalysisEx
ception: Unable to load DLL 'Microsoft.VisualStudio.Coverage.Symbols.dll':  (Exception from HRESULT: 0x8007007E) ---> System.DllNotFoundExcep
tion: Unable to load DLL 'Microsoft.VisualStudio.Coverage.Symbols.dll':  (Exception from HRESULT: 0x8007007E)
   at Microsoft.VisualStudio.Coverage.Analysis.Vsp.SymbolInterop.CreateSession()

   at Microsoft.VisualStudio.Coverage.Analysis.Vsp.VspSymbolReaderFactory.Create
Reader()
   at Microsoft.VisualStudio.Coverage.Analysis.CoverageInfo.BuildDataSet(Boolean
 summaryOnly, IEnumerable`1 tests, IEnumerable`1 modules)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Coverage.Analysis.CoverageInfo.BuildDataSet(Boolean
 summaryOnly, IEnumerable`1 tests, IEnumerable`1 modules)
   at Microsoft.VisualStudio.Coverage.Analysis.CoverageInfo.BuildDataSet()
   at VisualCoverage.Core.Util.MikeParser.Parse(String[] inputfiles)
   at VisualCoverage.Console.CmdDriver.Main(String[] args)

**Comment by jsargiot** [comment]
Sorry for the late response, but as a reference for the future, in this case you'll need to copy the `Microsoft.VisualStudio.Coverage.Symbols.dll` to the app folder
